module.exports = {
  action: 'button',
  // battery: 'battery',
  // battery_state: 'battery',
  brightness: 'brightness',
  carbon_monoxide: 'smoke',
  co2: 'co2',
  contact: 'door',
  cover_state: 'door',
  climate_local_temperature: 'temperature',
  current: 'current',
  energy: 'energy',
  gas: 'smoke',
  humidity: 'humidity',
  illuminance: 'illuminance',
  light_state: 'light',
  light_brightness: 'brightness',
  light_color_xy: 'color',
  light_color_temp: 'color_temperature',
  lock_state: 'door',
  occupancy: 'motion',
  pressure: 'pressure',
  power: 'power',
  smoke: 'smoke',
  switch_state: 'switch_sensor',
  temperature: 'temperature',
  voltage: 'voltage',
  water_leak: 'water',
};
